# Introduction to Numpy

NumPy is a Python library that allows you to work with vectors, matrices, and tensors easily.
You are advised to use conda as the environment manager. You can also install it with the following command:

```
pip install numpy matplotlib
```

This is a very, very rudimentary introductory version of NumPy. You are expected to learn more from the course Statistics for DS. To learn more about NumPy refer to (The Official Documentation)[https://numpy.org/doc/stable/user/whatisnumpy.html#] or refer to previous year's statistics for DS course tutorials at https://github.com/MandaKausthubh/AIM101-Statistics-For-DataScience-2025

In [1]:
import numpy as np
import matplotlib as plt

In [5]:
# Basic unit for computations in NumPy are ndarrays!!
a = np.array([1,2,3], dtype=np.float16)
b = np.array([[1,2,3],[4,5,6]], dtype=np.float32)

In [6]:
a

array([1., 2., 3.], dtype=float16)

In [7]:
b

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [9]:
a[0], b[0], b[0,1]

(np.float16(1.0), array([1., 2., 3.], dtype=float32), np.float32(2.0))

In [11]:
a[:2], b[0,1:2]

(array([1., 2.], dtype=float16), array([2.], dtype=float32))