# Auto Grad and Computational Graphs

Computational Graphs are an effective mechanism for implementing Backprop!! This idea of Computational 

In [1]:
from custom_autograd import Variable

In [2]:
x = Variable(5)
y = Variable(3)

z = x + y
w = x.sin()

l = z - w

In [3]:
l.backward()

In [4]:
x.grad, y.grad, z.grad, w.grad, l.grad

(np.float64(0.7163378145367738),
 np.float16(1.0),
 np.float16(1.0),
 np.float16(-1.0),
 np.float16(1.0))

Sanity Checking if our code is correct:
$
\frac{\partial l}{\partial x} = 1 - cos(x)
$

In [5]:
import numpy as np

1 - np.cos(5)  # x.grad

np.float64(0.7163378145367738)

In [6]:
from custom_vector_autograd import CustomTensorVariable

In [7]:
class Model:
    def __init__(self):
        self.layer1 = CustomTensorVariable(np.random.rand(10, 10).astype(np.float16))
        self.bias1 = CustomTensorVariable(np.random.rand(10, 1).astype(np.float16))
        self.layer2 = CustomTensorVariable(np.random.rand(1,  10).astype(np.float16))
        self.bias2 = CustomTensorVariable(np.random.rand(1, 1).astype(np.float16))

    def forward(self, x:CustomTensorVariable, verbose=False):
        out1 = self.layer1.matmul(x) + self.bias1
        if verbose: print(out1.value.shape)
        out1_5 = out1.ReLU()
        if verbose: print(out1_5.value.shape)
        out2 = self.layer2.matmul(out1_5) + self.bias2
        return out2

our_model = Model()

In [8]:
x = np.random.rand(10, 1).astype(np.float16)

pred = our_model.forward(x)

In [9]:
pred.value

array([[19.25]], dtype=float16)

In [10]:
loss = (pred - np.random.rand(1,1).astype(np.float16))**2

In [11]:
loss.backward()

In [12]:
our_model.layer1.grad

array([[18.25  , 17.    ,  7.75  , 23.67  , 16.89  , 23.92  , 14.016 ,
         2.973 ,  6.08  , 20.47  ],
       [29.    , 27.02  , 12.31  , 37.6   , 26.83  , 38.    , 22.27  ,
         4.723 ,  9.65  , 32.53  ],
       [ 6.27  ,  5.84  ,  2.662 ,  8.13  ,  5.8   ,  8.21  ,  4.812 ,
         1.0205,  2.086 ,  7.03  ],
       [ 3.174 ,  2.955 ,  1.348 ,  4.113 ,  2.936 ,  4.156 ,  2.436 ,
         0.5166,  1.057 ,  3.559 ],
       [13.22  , 12.31  ,  5.613 , 17.14  , 12.23  , 17.31  , 10.15  ,
         2.152 ,  4.4   , 14.82  ],
       [ 9.6   ,  8.94  ,  4.074 , 12.445 ,  8.875 , 12.57  ,  7.367 ,
         1.5625,  3.195 , 10.766 ],
       [17.75  , 16.53  ,  7.535 , 23.02  , 16.4   , 23.25  , 13.625 ,
         2.889 ,  5.906 , 19.9   ],
       [ 3.623 ,  3.373 ,  1.538 ,  4.695 ,  3.35  ,  4.746 ,  2.781 ,
         0.59  ,  1.205 ,  4.062 ],
       [19.27  , 17.94  ,  8.18  , 24.98  , 17.83  , 25.23  , 14.79  ,
         3.137 ,  6.414 , 21.61  ],
       [20.86  , 19.42  ,  8.86  , 27

In [13]:
our_model.bias1.grad

array([[24.  ],
       [38.12],
       [ 8.24],
       [ 4.17],
       [17.38],
       [12.62],
       [23.33],
       [ 4.76],
       [25.33],
       [27.42]], dtype=float16)

In [14]:
our_model.bias1.zero_grad()

In [15]:
our_model.bias1.grad

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float16)