### *Linear operators and matrices* are the **mathematical backbone** of machine learning, signal processing, and optimization.  
Every model you will build later is internally just **matrix operations executed at scale**.  
Mastering this now gives you **direct control** over how data is transformed, solved, and interpreted — instead of treating algorithms as black boxes.

---

### **What this notebook contains**

* **Vectors and matrices** as numerical objects  
* **Linear transformations** using matrix–vector multiplication  
* **Operator composition** using matrix–matrix multiplication  
* **Identity, determinant, inverse, and rank** of matrices  
* **Solving linear systems** of the form *(Ax = b)*  
* **Eigenvalues and eigenvectors** to expose the internal structure of a transformation  
* **Projection operators** for dimensional reduction  
* Matrices stored as **DataFrames**  
* Vectors stored as **Series**  
* **Labeled matrix multiplication**  
* **Structured result tables** for clean, report-ready output  

In [145]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [146]:
# --------------------------------------------------
# VECTOR DEFINITION AND MANIPULATION
# A vector is an ordered list of numbers representing a point or direction in space.
# Vectors support scaling, addition, and dot products.
# --------------------------------------------------

v1 = np.array([1, 2, 3, 5])
v2 = np.array([4, 5, 6, 7])
v_sum = v1 + v2
v_scaled = 2 * v1
dot_product = np.dot(v1, v2)
print("Vector Sum:", v_sum)
print("Scaled Vector:", v_scaled)
print("Dot Product:", dot_product)

Vector Sum: [ 5  7  9 12]
Scaled Vector: [ 2  4  6 10]
Dot Product: 67


In [147]:
# --------------------------------------------------
# MATRIX CONSTRUCTION AND DIMENSIONALITY
# A matrix is a rectangular grid of numbers representing a linear operator.
# Its shape (rows, columns) determines how it acts on vectors.
# --------------------------------------------------

A = np.array([[1, 2, 3],
                [4, 5, 6],
                [14, -15, -36],
                [7, 8, 9]])
shape_A = A.shape
print("Matrix A Shape:", shape_A)

Matrix A Shape: (4, 3)


In [148]:
# --------------------------------------------------
# MATRIX–VECTOR MULTIPLICATION
# A matrix applied to a vector computes a linear transformation.
# --------------------------------------------------

v = np.array([1, 0, -1])
Av = A @ v
print("Matrix-Vector Product Av:", Av)

Matrix-Vector Product Av: [-2 -2 50 -2]


In [149]:
# --------------------------------------------------
# MATRIX–MATRIX MULTIPLICATION
# Multiplying two matrices composes two linear transformations.
# --------------------------------------------------

B = np.array([[1, 0],
                [1, 0],
                [0, 1]])
AB = A @ B
print("Shape of Matrix A:", A.shape)
print("Shape of Matrix B:", B.shape)
print("Matrix-Matrix Product AB:\n", AB)

Shape of Matrix A: (4, 3)
Shape of Matrix B: (3, 2)
Matrix-Matrix Product AB:
 [[  3   3]
 [  9   6]
 [ -1 -36]
 [ 15   9]]


In [150]:
# --------------------------------------------------
# IDENTITY OPERATORS
# The identity matrix leaves all vectors unchanged when applied.
# --------------------------------------------------

I = np.eye(3)
A_identity = A @ I
print("A multiplied by Identity Matrix:\n", A_identity)

A multiplied by Identity Matrix:
 [[  1.   2.   3.]
 [  4.   5.   6.]
 [ 14. -15. -36.]
 [  7.   8.   9.]]


In [151]:
# --------------------------------------------------
# DETERMINANT AND INVERTIBILITY
# The determinant measures how volume is scaled by a matrix.
# If det = 0, the matrix is not invertible.
# --------------------------------------------------
C = np.array([[4, 2, 11],
                [3, 1, 5],
                [7, 8, 9]])
detC = np.linalg.det(C)
print("Determinant of C:", detC)

Determinant of C: 79.0


In [152]:
# --------------------------------------------------
# MATRIX INVERSE
# The inverse matrix reverses the effect of the original matrix.
# --------------------------------------------------

# Using a non-singular matrix
M = np.array([[2, 1 ,10],
                [1, 1, 5],
                [3, 4, 6]])
M_inv = np.linalg.inv(M)
print("Matrix M Inverse:\n", M_inv)

Matrix M Inverse:
 [[ 1.55555556 -3.77777778  0.55555556]
 [-1.          2.         -0.        ]
 [-0.11111111  0.55555556 -0.11111111]]


In [153]:
# --------------------------------------------------
# SOLVING LINEAR SYSTEMS
# Solving Ax = b finds the vector x that produces b when transformed by A.
# --------------------------------------------------

b = np.array([5, 9, 4])
x = np.linalg.solve(M, b)
print("Matrix M:\n", M)
print("Solution x of Mx = b:", x)

Matrix M:
 [[ 2  1 10]
 [ 1  1  5]
 [ 3  4  6]]
Solution x of Mx = b: [-24.  13.   4.]


In [154]:
# --------------------------------------------------
# EIGENVALUES AND EIGENVECTORS
# Eigenvectors remain in the same direction when transformed.
# Eigenvalues give the scaling factor.
# --------------------------------------------------

eigvals, eigvecs = np.linalg.eig(M)
print("Eigenvalues of M:", eigvals)
print("Eigenvectors of M:\n", eigvecs)

Eigenvalues of M: [11.60453667  0.26981995 -2.87435662]
Eigenvectors of M:
 [[-0.69041881 -0.85856376 -0.82694649]
 [-0.36075302  0.50320961 -0.35220627]
 [-0.62703997  0.09822603  0.43830383]]


In [155]:
# --------------------------------------------------
# RANK DIAGNOSTICS
# The rank tells how many independent directions the matrix preserves.
# --------------------------------------------------

rank_M = np.linalg.matrix_rank(M)
print("Rank of Matrix M:", rank_M)

Rank of Matrix M: 3


In [156]:
# --------------------------------------------------
# PROJECTION OPERATORS
# A projection matrix maps vectors onto a specific direction or subspace.
# --------------------------------------------------

u = np.array([1, 1])
P = np.outer(u, u) / (u @ u)
projection_of_v = P @ np.array([2, 0])
print("Projection of vector [2, 0] onto u:", projection_of_v)

Projection of vector [2, 0] onto u: [1. 1.]


In [157]:
# --------------------------------------------------
# OPERATOR COMPOSITION
# Applying two linear operators in sequence is matrix multiplication.
# --------------------------------------------------

T1 = np.array([[1, 2, 3],
                [-5, -6, -4]])
T2 = np.array([[12, 4],
                [19, 6],
                [1, 1]])
T3 = np.array([[0, 1 ,9],
                [1, 0, -11]])
T_composed = T1 @ T2 @ T3
print("Composed Operator T1 @ T2 @ T3:\n", T_composed)

Composed Operator T1 @ T2 @ T3:
 [[  19   53  268]
 [ -60 -178 -942]]


In [158]:
# --------------------------------------------------
# PANDAS: MATRICES AS DATAFRAMES
# A DataFrame stores a matrix with labeled rows and columns.
# --------------------------------------------------

M_df = pd.DataFrame(M, columns=["x1", "x2", "x3"], index=["y1", "y2", "y3"])
print("DataFrame Representation of M:\n", M_df)

DataFrame Representation of M:
     x1  x2  x3
y1   2   1  10
y2   1   1   5
y3   3   4   6


In [159]:
# --------------------------------------------------
# PANDAS: VECTORS AS SERIES
# A Series stores a labeled vector.
# --------------------------------------------------

v_series = pd.Series([1, 2, 3], index=["x1", "x2", "x3"])
print("Series Representation of v:\n", v_series)

Series Representation of v:
 x1    1
x2    2
x3    3
dtype: int64


In [160]:
# --------------------------------------------------
# LABELED MATRIX–VECTOR MULTIPLICATION
# Pandas aligns labels before multiplying.
# --------------------------------------------------

Mv = M_df @ v_series
print("Labeled Matrix-Vector Product Mv:\n", Mv)

Labeled Matrix-Vector Product Mv:
 y1    34
y2    18
y3    29
dtype: int64


In [161]:
# --------------------------------------------------
# STORING OPERATORS IN TABULAR FORM
# Multiple matrices can be organized for analysis and reporting.
# --------------------------------------------------

operators = {
    "M11": M[0,0],
    "M12": M[0,1],
    "M21": M[1,0],
    "M22": M[1,1]
}
operators_df = pd.DataFrame([operators])
print("Operators Stored in DataFrame:\n", operators_df)

Operators Stored in DataFrame:
    M11  M12  M21  M22
0    2    1    1    1


In [162]:
# --------------------------------------------------
# STRUCTURING NUMERICAL OUTPUTS FOR REPORTING
# Pandas provides clean formatting of computed results.
# --------------------------------------------------

results_df = pd.DataFrame({
    "b": b,
    "x_solution": x
})
print("Results DataFrame:\n", results_df)

Results DataFrame:
    b  x_solution
0  5       -24.0
1  9        13.0
2  4         4.0


In [163]:
# --------------------------------------------------
# SUMMARY DATAFRAME GENERATION
# All key results can be consolidated for presentation.
# --------------------------------------------------

summary_df = pd.DataFrame({
    "Eigenvalues": eigvals,
    "Rank": np.full(len(eigvals), rank_M)
})
print("Summary DataFrame:\n", summary_df)

Summary DataFrame:
    Eigenvalues  Rank
0    11.604537     3
1     0.269820     3
2    -2.874357     3


In [164]:
# A company has 3 products. Each product uses 3 resources (labor, material, energy).
# The matrix M encodes how much of each resource each product consumes.
# The vector x is how many units of each product we produce.
# The result M @ x gives total resource usage.

# Resource consumption matrix (rows = resources, columns = products)
M = np.array([
    [2, 1, 3],   # labor per product
    [4, 2, 1],   # material per product
    [3, 5, 2]    # energy per product
])

# Production plan (units of each product)
x = np.array([100, 150, 80])

# Total resource usage
b = M @ x

# Put everything into Pandas for reporting
M_df = pd.DataFrame(M, index=["Labor", "Material", "Energy"], columns=["Product_A", "Product_B", "Product_C"])

x_series = pd.Series(x, index=M_df.columns, name="Units_Produced")
b_series = pd.Series(b, index=M_df.index, name="Total_Used")

report = pd.concat([M_df, pd.DataFrame(x_series).T], axis=0)

summary = pd.DataFrame({
    "Total_Usage": b_series
})

print("Resource Matrix:\n", M_df)
print("\nProduction Plan:\n", x_series)
print("\nTotal Resource Usage:\n", b_series)
print("\nSummary Table:\n", summary)





Resource Matrix:
           Product_A  Product_B  Product_C
Labor             2          1          3
Material          4          2          1
Energy            3          5          2

Production Plan:
 Product_A    100
Product_B    150
Product_C     80
Name: Units_Produced, dtype: int64

Total Resource Usage:
 Labor        590
Material     780
Energy      1210
Name: Total_Used, dtype: int64

Summary Table:
           Total_Usage
Labor             590
Material          780
Energy           1210
